# Generated by Django 4.2.3 on 2023-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_number_of_emails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userСategories",
        ),
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.JSONField(default={"credit": [], "debit": []}),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.CharField(default=0, max_length=30),
        ),
    ]
