# Generated by Django 4.2.3 on 2023-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_delete_userсategories_profile_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="category",
            field=models.JSONField(default={}),
        ),
    ]
