# Generated by Django 4.2.3 on 2023-08-31 16:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="category",
            field=models.JSONField(default=account.models.get_default_something),
        ),
    ]
