# Generated by Django 4.2.3 on 2023-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("categoty", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("priority", models.IntegerField()),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
            },
        ),
        migrations.CreateModel(
            name="debit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("categoty", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                "verbose_name": "Доход",
                "verbose_name_plural": "Доходы",
            },
        ),
    ]
