# Generated by Django 4.2.3 on 2023-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debit",
            name="categoty",
            field=models.CharField(max_length=100),
        ),
    ]
