# Generated by Django 4.2.3 on 2023-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debit", "0004_rename_debit_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="date",
            field=models.CharField(),
        ),
    ]
